### ISSUE TITLE
ERROR: this R is version 3.2.2, package 'simcdm' requires R >= 3.3.0

### ISSUE THREAD

**Issue by genwei007** [tmsalab/simcdm#1]
Can simcdm support 3.2.2? Thanks!

**Comment by coatless** [comment]
Hi @genwei007 could you explain why you need it on _R_ 3.2.2? _R_ 3.3.0 and higher have unified support for _C++11_.

**Comment by genwei007** [comment]
Hi @coatless The reason is that I used R 3.2.2 for the IDE of revolution R. However, it is not updated anymore. So I just keep using the old R version. It will be great if no version restriction. Thank you 👍

**Comment by coatless** [comment]
@genwei007 looks like it is still being updated:

https://mran.microsoft.com/download

**Comment by genwei007** [comment]
@coatless Sorry, I missed to indicate that I use https://docs.microsoft.com/en-us/machine-learning-server/install/r-server-install-windows-800 which has a IDE, not the Microsoft R Open. I stick to this only because its convenient IDE. Or, can I force old R version to install the package?

**Comment by coatless** [comment]
You should be able to update the version of _R_ being used by the IDE. 

Note:

> Revolution R Enterprise 2016 for Windows is installed in two steps: first, you install **Microsoft R Open for Revolution R Enterprise**, and then install Revolution R Enterprise itself. This document assumes you have access to the Revolution R Enterprise installer, which is available either through your Volume Licensing agreement or an MSDN subscription.

(I've bolded the MRO statement)

Unless I'm missing something, this should work in a similar way to RStudio... You need to install the _R_ language first, then the IDE. 

Thus, could you try upgrading MRO? Sorry if this seems circular. There are more dragons on R 3.2.* vs. R 3.3.* when it comes to compiled code.

**Comment by genwei007** [comment]
Thanks. Actually, it is a special version of Microsoft R Open **ONLY** for Revolution R Enterprise. For example, I install by the file "MRO-3.2.2-for-RRE-8.0.0-Windows.exe", not the regular Microsoft R Open. The download link has been removed, because it is not updated anymore.

If it is not good idea to use old R version, I'll try to use the latest R version. Thank you anyway:)

**Comment by coatless** [comment]
@genwei007 Aye. If you could upgrade to _R 3.3.*_ (2016) or _R 3.4.*_ (2017) that would be appreciated.
